### ISSUE TITLE
Candle becomes NullReferenceException, can't drop from inventory.

### ISSUE THREAD

**Issue by mmyang** [DigitalzombieTLD/Candlelight#14]
Loaded game where I had been creating and using candles for several days / saves.  MelonLoader window started spamming the following message, repeated:

[23:53:27.016] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NullReferenceException: Object reference not set to an instance of an object.
   at Candlelight.SaveLoad.SetLitState(String candleID, Boolean litState)
   at Candlelight.CandleItem.turnOff()
   at Candlelight.CandleItem.Update()
   at Trampoline_VoidThisCandlelight.CandleItemUpdate(IntPtr , Il2CppMethodInfo* )

I saw it looked like an issue with the candles so I picked up the two candles that I had placed in the environment (Forsaken Airfield hanger indoors).  When I picked up the second of the two candles, the message stopped spamming.

I tried to drop one of the candles from my inventory, it failed to drop.  All other candles failed to drop from inventory, but could be moved between inventory and a container.  Each attempt to drop a candle resulted in the following error message from MelonLoader:

[23:59:07.039] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NullReferenceException: Object reference not set to an instance of an object.
   at Candlelight.SaveLoad.SetLitState(String candleID, Boolean litState)
   at Candlelight.CandleItem.Awake()
   at Trampoline_VoidThisCandlelight.CandleItemAwake(IntPtr , Il2CppMethodInfo* )
[23:59:07.039] During invoking native->managed trampoline

I was running version 1.6 of the mod.  I updated to 1.7.  The original problematic save still encounters the same behavior, can't drop the candles.  I've started a new game in 1.7 and created some candles but I don't know what triggered the corruption of the candles initially, since I'd already been playing with candles for several days (saves and loads) by that point.

[02:17:31.240] ------------------------------
[02:17:31.240] MelonLoader v0.6.1 Open-Beta
[02:17:31.241] OS: Windows 10
[02:17:31.322] ------------------------------
[02:17:31.322] Game Name: TheLongDark
[02:17:31.322] Game Developer: Hinterland
[02:17:31.323] Unity Version: 2021.3.16f1
[02:17:31.323] Game Version: 2.24
[02:17:31.324] ------------------------------

**Comment by mmyang** [comment]
I started a new custom run on 1.7 to see if I could reproduce the error.I was getting the spammed `Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.NullReferenceException` message and instead of touching the candles I had placed I exited the Forsaken Airfield hanger.  The message stopped when the scene changed, and did not resume when I re-entered the hanger.  I was still able to pick up and drop candles.

Then I loaded my old save game that was having the problems with dropping candles and I can drop those candles now, so it looks like whatever was broken at least didn't corrupt my save file.

Thanks for this mod, by the way. Having candles is really fun.
